notifications:
  email: false

language: c

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: windows

before_script:
  - cmake --version

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && cmake --build .

after_success:
  - ctest -C Debug
