notifications:
  email: false

language: python
python: "3.8"

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: windows

before_script:
  - cmake --version

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug && cmake --build .
  - cd ${TRAVIS_BUILD_DIR}/src/python && pip install .


after_success:
  - cd ${TRAVIS_BUILD_DIR}/build && ctest -C Debug
  - cd ${TRAVIS_BUILD_DIR}/src/python && pytest
